"""Tests for genetic data file parser."""
from __future__ import annotations

from healthbot.ingest.genetic_parser import GeneticParser

TELLMEGEN_SAMPLE = """\
# TellMeGen raw data export
# rsid\tchromosome\tposition\tgenotype
rsid\tchromosome\tposition\tgenotype
rs1800562\t6\t26093141\tAG
rs1799945\t6\t26091179\tCG
rs1801133\t1\t11856378\tCT
rs4988235\t2\t136608646\tAG
"""

TWENTYTHREEANDME_SAMPLE = """\
# This data file generated by 23andMe
#
# rsid\tchromosome\tposition\tgenotype
rs1800562\t6\t26093141\tAG
rs6025\t1\t169519049\tAG
rs762551\t15\t75041917\tAC
"""

ANCESTRY_SAMPLE = """\
# AncestryDNA raw data
rsid\tchromosome\tposition\tallele1\tallele2
rs1800562\t6\t26093141\tA\tG
rs1801133\t1\t11856378\tC\tT
rs4244285\t10\t96541616\tA\tG
"""

CSV_SAMPLE = """\
rsid,chromosome,position,genotype
rs1800562,6,26093141,AG
rs1801133,1,11856378,CT
"""


class TestGeneticParser:

    def test_parse_tellmegen_format(self):
        parser = GeneticParser()
        result = parser.parse(TELLMEGEN_SAMPLE)
        assert result.source == "tellmegen"
        assert len(result.variants) == 4
        assert result.skipped_lines == 0
        assert result.variants[0].rsid == "rs1800562"
        assert result.variants[0].genotype == "AG"
        assert result.variants[0].chromosome == "6"
        assert result.variants[0].position == 26093141

    def test_parse_23andme_format(self):
        parser = GeneticParser()
        result = parser.parse(TWENTYTHREEANDME_SAMPLE)
        assert len(result.variants) == 3
        assert result.variants[0].rsid == "rs1800562"

    def test_parse_ancestry_format(self):
        parser = GeneticParser()
        result = parser.parse(ANCESTRY_SAMPLE)
        assert result.source == "ancestry"
        assert len(result.variants) == 3
        # Ancestry splits alleles — parser combines them
        assert result.variants[0].genotype == "AG"
        assert result.variants[1].genotype == "CT"

    def test_parse_csv_format(self):
        parser = GeneticParser()
        result = parser.parse(CSV_SAMPLE)
        assert len(result.variants) == 2
        assert result.variants[0].rsid == "rs1800562"

    def test_parse_bytes_input(self):
        parser = GeneticParser()
        result = parser.parse(TELLMEGEN_SAMPLE.encode("utf-8"))
        assert len(result.variants) == 4

    def test_parse_empty_file(self):
        parser = GeneticParser()
        result = parser.parse("")
        assert len(result.variants) == 0
        assert result.total_lines == 0

    def test_parse_comments_only(self):
        parser = GeneticParser()
        result = parser.parse("# Just comments\n# Nothing here\n")
        assert len(result.variants) == 0

    def test_skip_malformed_lines(self):
        data = "rsid\tchromosome\tposition\tgenotype\n"
        data += "rs1800562\t6\t26093141\tAG\n"  # valid
        data += "bad_line\n"  # malformed
        data += "rs1801133\t1\tnot_a_number\tCT\n"  # bad position
        data += "rs6025\t1\t169519049\tXX\n"  # bad genotype
        data += "rs4988235\t2\t136608646\tAG\n"  # valid

        parser = GeneticParser()
        result = parser.parse(data)
        assert len(result.variants) == 2
        assert result.skipped_lines == 3
        assert len(result.warnings) > 0

    def test_genotype_validation(self):
        parser = GeneticParser()
        # Valid genotypes
        for gt in ["AA", "AG", "CC", "CT", "GG", "AT", "A", "DI", "--"]:
            data = f"rsid\tchromosome\tposition\tgenotype\nrs123\t1\t100\t{gt}\n"
            result = parser.parse(data)
            assert len(result.variants) == 1, f"Failed for genotype: {gt}"

        # Invalid genotypes
        for gt in ["XY", "123", "ACGT", ""]:
            data = f"rsid\tchromosome\tposition\tgenotype\nrs123\t1\t100\t{gt}\n"
            result = parser.parse(data)
            assert len(result.variants) == 0, f"Should reject genotype: {gt}"

    def test_explicit_source_override(self):
        parser = GeneticParser()
        result = parser.parse(TELLMEGEN_SAMPLE, source="23andme")
        assert result.source == "23andme"
        for v in result.variants:
            assert v.source == "23andme"

    def test_auto_detect_format(self):
        parser = GeneticParser()
        lines = ANCESTRY_SAMPLE.splitlines()
        assert parser._detect_format(lines) == "ancestry"

    def test_i_prefix_rsids_accepted(self):
        """Internal SNPs (i-prefix) used by some providers."""
        data = "rsid\tchromosome\tposition\tgenotype\ni1234\t1\t100\tAG\n"
        parser = GeneticParser()
        result = parser.parse(data)
        assert len(result.variants) == 1
        assert result.variants[0].rsid == "i1234"
